{
 "title": "Cloudnative PostgreSQL Database Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(cnpg_collector_up,namespace)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cnpg_collector_up,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL Health & Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_collector_up{namespace=\"$Namespace\", cluster=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnpg_backends_total{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\"}) by (usename)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cnpg_pg_replication_lag{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "At its core, Cache Hit Ratio is the ultimate measure of how efficiently your database is using its memory (RAM)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_blks_hit_total{namespace=\"$Namespace\"}[10m]))\n/\n(sum(rate(cnpg_pg_stat_database_blks_hit_total{namespace=\"$Namespace\"}[10m])) + sum(rate(cnpg_pg_stat_database_blks_read_total{namespace=\"$Namespace\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Commit Rate",
   "type": "bargauge",
   "description": "Transaction Commit Rate is the most direct measurement of how much actual work your database is accomplishing at any given moment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit_total{namespace=\"$Namespace\"}[5m])) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnpg_pg_database_size_bytes{namespace=\"$Namespace\"}) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backup & WAL Archiving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "WAL Archiving Rate Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnpg_pg_stat_archiver_archived_count_total{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Archiving Rate Failure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnpg_pg_stat_archiver_failed_count_total{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Size on Disk",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_wal_bytes{namespace=\"$Namespace\", pod=\"$Cluster-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware & Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  label_replace(\n    rate(container_cpu_usage{job=~\"^$Namespace/$Cluster-.*\"}[5m]), \n    \"pod\", \n    \"$1\", \n    \"job\", \n    \".*/(.*)\"\n  )\n) / max(kube_pod_container_resource_limits{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  label_replace(\n    container_memory_usage_bytes{job=~\"^$Namespace/$Cluster-.*\"}, \n    \"pod\", \n    \"$1\", \n    \"job\", \n    \".*/(.*)\"\n  )\n) \n/ \nmax by (pod) (\n  kube_pod_container_resource_limits{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\", resource=\"memory\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (\n  kube_pod_container_status_restarts_total{namespace=\"$Namespace\", pod=~\"^$Cluster-.*\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Logging",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "desc",
     "expr": "cnpg.io/cluster: \"$Cluster\" AND k8s.namespace.name: \"$Namespace\""
    }
   ]
  }
 ]
}